server:
   port: 8761
spring:
   application:
      name: microservice-center
eureka:
   client:
      registerWithEureka: false # 表示是否将自己注册到Eureka Server,默认为true，
      fetchRegistry: false # 表示是否从Eureka Server获取注册信息，默认为true,因为当前为单点Eureka Server，所以不需要从别的Eureka Server上获取信息
      serviceUrl:
         # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认为http://localhost:8761/eureka/，多个地址可用“，”分割
         defaultZone: http://localhost:8761/eureka/